version: '2'
services:
  web:
    build: .
    command: python -u main.py
    ports:
      - "17000:5000"
    volumes:
      - .:/code
    links:
      - db
  db:
    image: mongo:3.4
    command: --smallfiles --rest
